---
- hosts: self
  user: admin
  connection: local

  vars_files:
    - vars/main.yml

  tasks:
    - name: Ensure Ansible downloads directory exists.
      file:
        path: "{{ downloads }}"
        state: directory

    - include: tasks/dotfiles.yml
    - include: tasks/preferences.yml

    - name: Get list of apps installed with cask.
      command: brew cask list
      register: homebrew_cask_list
      changed_when: false

    - name: Install apps via `brew cask`.
      command: >
        brew cask install {{ item }} --appdir={{ homebrew_cask_appdir }}
      with_items: homebrew_cask_apps
      when: "'{{ item }}' not in homebrew_cask_list.stdout"
